apiVersion: 1

datasources:
  - name: MySQL-Auth-Audit
    uid: mysql-auth-audit
    type: mysql
    access: proxy
    url: ${GRAFANA_MYSQL_HOST}
    user: ${GRAFANA_MYSQL_USER}
    database: ${GRAFANA_MYSQL_DATABASE}
    editable: true
    jsonData:
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      tlsSkipVerify: true
    secureJsonData:
      password: ${GRAFANA_MYSQL_PASSWORD}
