import {
  Bot,
  CircleDot,
  FileInput,
  FileOutput,
  FileText,
  GitBranch,
  Image,
  Mic,
  Play,
  Repeat,
  UserRoundPen,
  Video,
  Wrench,
  type LucideIcon as LucideIconType,
} from "lucide-react"
import type { AgentModelConfig } from "@/lib/api/types"

export interface NodeTypeDefinition {
  type: string
  category: string
  displayName: string
  description: string
  icon: LucideIconType
  iconName: string
  color: string
  defaultWidth: number
  defaultHeight: number
  defaultData: Partial<{
    title: string
    detail: string
    kind: string
    iconName: string
    color: string
    config: AgentModelConfig | null
    parameters: Record<string, unknown>
  }>
  inputSlots: Array<{ name: string; type: string; label: string }>
  outputSlots: Array<{ name: string; type: string; label: string }>
  parameters?: Array<{
    name: string
    label: string
    type: "string" | "number" | "boolean" | "select" | "model_selector"
    default?: unknown
    options?: Array<{ label: string; value: string }>
  }>
}

export const NODE_TYPES: NodeTypeDefinition[] = [
  {
    type: "field_input",
    category: "输入",
    displayName: "用户输入参数",
    description: "配置用户侧表单字段、填写方式、选项和必填规则。",
    icon: FileInput,
    iconName: "file-input",
    color: "#475569",
    defaultWidth: 320,
    defaultHeight: 220,
    defaultData: { kind: "input", iconName: "file-input" },
    inputSlots: [],
    outputSlots: [{ name: "params", type: "json", label: "用户填写参数" }],
  },
  {
    type: "prompt_template",
    category: "编排",
    displayName: "提示词组装",
    description: "把用户参数整理成后续模型或工具需要的提示词。",
    icon: FileText,
    iconName: "file-text",
    color: "#b45309",
    defaultWidth: 280,
    defaultHeight: 150,
    defaultData: { kind: "prompt", iconName: "file-text" },
    inputSlots: [{ name: "params", type: "json", label: "用户填写参数" }],
    outputSlots: [{ name: "prompt", type: "text", label: "组装后提示词" }],
    parameters: [
      { name: "template", label: "提示词模板", type: "string", default: "{{用户输入参数}}" },
      { name: "progressStep", label: "进度文案", type: "string", default: "整理用户输入" },
    ],
  },
  {
    type: "llm_model",
    category: "模型",
    displayName: "大模型统一节点",
    description: "选择系统配置里的模型，执行文本、图片、语音或视频类生成能力。",
    icon: Bot,
    iconName: "bot",
    color: "#2563eb",
    defaultWidth: 300,
    defaultHeight: 170,
    defaultData: { kind: "model", iconName: "bot" },
    inputSlots: [{ name: "prompt", type: "text", label: "模型输入" }],
    outputSlots: [{ name: "result", type: "any", label: "模型输出" }],
    parameters: [
      { name: "modelConfigId", label: "使用模型", type: "model_selector", default: null },
      { name: "progressStep", label: "进度文案", type: "string", default: "调用大模型" },
    ],
  },
  {
    type: "backend_tool",
    category: "工具",
    displayName: "后端工具统一节点",
    description: "调用 worker 或后端内置工具，例如字幕、音视频合成、报告导出。",
    icon: Wrench,
    iconName: "wrench",
    color: "#ea580c",
    defaultWidth: 300,
    defaultHeight: 160,
    defaultData: { kind: "tool", iconName: "wrench" },
    inputSlots: [{ name: "input", type: "any", label: "工具输入" }],
    outputSlots: [{ name: "output", type: "any", label: "工具输出" }],
    parameters: [
      { name: "toolName", label: "工具名称", type: "string", default: "后端工具" },
      { name: "progressStep", label: "进度文案", type: "string", default: "执行后端工具" },
    ],
  },
  {
    type: "final_output",
    category: "输出",
    displayName: "输出节点",
    description: "定义用户侧最终看到的文本、图片、视频或文件结果。",
    icon: FileOutput,
    iconName: "file-output",
    color: "#dc2626",
    defaultWidth: 280,
    defaultHeight: 140,
    defaultData: { kind: "output", iconName: "file-output" },
    inputSlots: [{ name: "result", type: "any", label: "最终结果" }],
    outputSlots: [],
    parameters: [
      {
        name: "displayMode",
        label: "展示方式",
        type: "select",
        default: "mixed",
        options: [
          { label: "文本", value: "text" },
          { label: "图片", value: "image" },
          { label: "音频", value: "audio" },
          { label: "视频", value: "video" },
          { label: "文件", value: "file" },
          { label: "混合结果", value: "mixed" },
        ],
      },
    ],
  },
  {
    type: "start",
    category: "编排",
    displayName: "开始",
    description: "工作流入口，传递会话上下文。",
    icon: Play,
    iconName: "play",
    color: "#10b981",
    defaultWidth: 180,
    defaultHeight: 100,
    defaultData: { kind: "start", iconName: "play" },
    inputSlots: [],
    outputSlots: [{ name: "context", type: "json", label: "会话上下文" }],
  },
  {
    type: "user_input",
    category: "输入",
    displayName: "用户补充输入",
    description: "分步收集脚本、分镜、场景图、BGM 等阶段意见。",
    icon: UserRoundPen,
    iconName: "user-round-pen",
    color: "#0ea5e9",
    defaultWidth: 260,
    defaultHeight: 150,
    defaultData: { kind: "input", iconName: "user-round-pen" },
    inputSlots: [{ name: "upstream", type: "any", label: "上一步结果" }],
    outputSlots: [{ name: "feedback", type: "text", label: "用户意见" }],
    parameters: [
      { name: "fieldKey", label: "字段键", type: "string", default: "scriptFeedback" },
      { name: "stageLabel", label: "阶段文案", type: "string", default: "脚本意见" },
    ],
  },
  {
    type: "llm_text",
    category: "模型",
    displayName: "剧本规划器",
    description: "根据初始表单生成剧本与分镜 JSON。",
    icon: Bot,
    iconName: "bot",
    color: "#3b82f6",
    defaultWidth: 300,
    defaultHeight: 170,
    defaultData: { kind: "model", iconName: "bot" },
    inputSlots: [{ name: "form", type: "json", label: "初始表单" }],
    outputSlots: [{ name: "script", type: "json", label: "剧本分镜" }],
    parameters: [
      { name: "modelConfigId", label: "使用模型", type: "model_selector", default: null },
      { name: "role", label: "节点角色", type: "string", default: "comic_script_planner" },
      { name: "progressStep", label: "进度文案", type: "string", default: "生成剧本与分镜" },
    ],
  },
  {
    type: "image_model",
    category: "模型",
    displayName: "关键帧生图",
    description: "根据剧本分镜生成电影感关键帧。",
    icon: Image,
    iconName: "image",
    color: "#ec4899",
    defaultWidth: 300,
    defaultHeight: 170,
    defaultData: { kind: "model", iconName: "image" },
    inputSlots: [
      { name: "script", type: "json", label: "剧本分镜" },
      { name: "form", type: "json", label: "表单参数" },
    ],
    outputSlots: [{ name: "keyframe", type: "image", label: "关键帧" }],
    parameters: [
      { name: "modelConfigId", label: "使用模型", type: "model_selector", default: null },
      { name: "progressStep", label: "进度文案", type: "string", default: "生成电影感关键帧" },
    ],
  },
  {
    type: "tts_model",
    category: "模型",
    displayName: "角色配音",
    description: "根据对白生成 TTS 音频。",
    icon: Mic,
    iconName: "mic",
    color: "#8b5cf6",
    defaultWidth: 280,
    defaultHeight: 160,
    defaultData: { kind: "model", iconName: "mic" },
    inputSlots: [{ name: "script", type: "json", label: "剧本分镜" }],
    outputSlots: [{ name: "audio", type: "audio", label: "配音音频" }],
    parameters: [
      { name: "modelConfigId", label: "使用模型", type: "model_selector", default: null },
      { name: "progressStep", label: "进度文案", type: "string", default: "生成角色配音" },
    ],
  },
  {
    type: "video_model",
    category: "模型",
    displayName: "图生视频",
    description: "根据关键帧与参数生成视频片段。",
    icon: Video,
    iconName: "video",
    color: "#f97316",
    defaultWidth: 300,
    defaultHeight: 170,
    defaultData: { kind: "model", iconName: "video" },
    inputSlots: [
      { name: "keyframe", type: "image", label: "关键帧" },
      { name: "script", type: "json", label: "剧本分镜" },
    ],
    outputSlots: [{ name: "clip", type: "video", label: "视频片段" }],
    parameters: [
      { name: "modelConfigId", label: "使用模型", type: "model_selector", default: null },
      { name: "progressStep", label: "进度文案", type: "string", default: "图生视频" },
    ],
  },
  {
    type: "subtitle",
    category: "工具",
    displayName: "字幕合成",
    description: "合并配音、视频片段并烧录字幕。",
    icon: Wrench,
    iconName: "wrench",
    color: "#f97316",
    defaultWidth: 280,
    defaultHeight: 150,
    defaultData: { kind: "tool", iconName: "wrench" },
    inputSlots: [
      { name: "clip", type: "video", label: "视频片段" },
      { name: "audio", type: "audio", label: "配音音频" },
      { name: "script", type: "json", label: "剧本分镜" },
    ],
    outputSlots: [{ name: "finalVideo", type: "video", label: "成片" }],
    parameters: [{ name: "progressStep", label: "进度文案", type: "string", default: "字幕与音视频合成" }],
  },
  {
    type: "video_output",
    category: "输出",
    displayName: "成片输出",
    description: "用户侧播放最终漫剧视频。",
    icon: FileOutput,
    iconName: "file-output",
    color: "#ef4444",
    defaultWidth: 260,
    defaultHeight: 130,
    defaultData: { kind: "output", iconName: "file-output" },
    inputSlots: [{ name: "finalVideo", type: "video", label: "成片" }],
    outputSlots: [],
    parameters: [{ name: "displayMode", label: "展示方式", type: "select", default: "video" }],
  },
  {
    type: "user_confirm",
    category: "编排",
    displayName: "用户确认",
    description: "等待用户确认上一步产物后继续。",
    icon: CircleDot,
    iconName: "circle-dot",
    color: "#14b8a6",
    defaultWidth: 220,
    defaultHeight: 120,
    defaultData: { kind: "confirm", iconName: "circle-dot" },
    inputSlots: [{ name: "artifact", type: "any", label: "待确认结果" }],
    outputSlots: [{ name: "confirmed", type: "any", label: "确认结果" }],
    parameters: [{ name: "sourceNodeId", label: "来源节点", type: "string", default: "" }],
  },
  {
    type: "condition",
    category: "编排",
    displayName: "条件判断",
    description: "根据用户是否填写修订意见决定分支。",
    icon: GitBranch,
    iconName: "git-branch",
    color: "#a855f7",
    defaultWidth: 240,
    defaultHeight: 130,
    defaultData: { kind: "condition", iconName: "git-branch" },
    inputSlots: [
      { name: "upstream", type: "any", label: "上游结果" },
      { name: "revision", type: "text", label: "修订意见" },
    ],
    outputSlots: [{ name: "next", type: "any", label: "继续执行" }],
    parameters: [{ name: "revisionField", label: "修订字段", type: "string", default: "scriptFeedback" }],
  },
  {
    type: "scene_loop",
    category: "编排",
    displayName: "分镜循环",
    description: "按时长字段自动拆分分镜数（如 30s ÷ 5s/镜 = 6 镜），下游模型节点逐镜生成并合成。",
    icon: Repeat,
    iconName: "repeat",
    color: "#eab308",
    defaultWidth: 260,
    defaultHeight: 150,
    defaultData: { kind: "loop", iconName: "repeat" },
    inputSlots: [{ name: "form", type: "json", label: "用户填写参数" }],
    outputSlots: [{ name: "loop", type: "json", label: "分镜计划(sceneCount/indices)" }],
    parameters: [
      { name: "durationField", label: "时长字段", type: "string", default: "episodeLength" },
      { name: "secondsPerScene", label: "每镜时长(秒)", type: "number", default: 5 },
      { name: "maxScenes", label: "最大分镜数", type: "number", default: 18 },
    ],
  },
  // ===== AI 漫剧 SOP 节点（见 docs/AI漫剧工作流完整交付计划书.md §5）=====
  {
    type: "script_planner",
    category: "创意策划",
    displayName: "剧本策划",
    description: "生成系列策划、世界观、分集大纲与样例剧本（钩子-冲突-反转-悬念）。",
    icon: FileText,
    iconName: "file-text",
    color: "#3b82f6",
    defaultWidth: 300,
    defaultHeight: 170,
    defaultData: { kind: "model", iconName: "file-text" },
    inputSlots: [
      { name: "form", type: "json", label: "项目参数" },
      { name: "loop", type: "json", label: "分镜计划" },
    ],
    outputSlots: [{ name: "script", type: "json", label: "剧本/分集大纲" }],
    parameters: [
      { name: "modelConfigId", label: "使用模型", type: "model_selector", default: null },
      { name: "role", label: "节点角色", type: "string", default: "comic_script_planner" },
      { name: "progressStep", label: "进度文案", type: "string", default: "生成系列策划与剧本" },
    ],
  },
  {
    type: "storyboard_generator",
    category: "创意策划",
    displayName: "分镜拆解",
    description: "把剧本翻译为镜头语言：镜号、景别、运镜、画面描述、台词、时长、首尾帧/视频 Prompt。",
    icon: FileText,
    iconName: "file-text",
    color: "#6366f1",
    defaultWidth: 300,
    defaultHeight: 170,
    defaultData: { kind: "model", iconName: "file-text" },
    inputSlots: [{ name: "script", type: "json", label: "剧本/大纲" }],
    outputSlots: [{ name: "storyboard", type: "json", label: "分镜表" }],
    parameters: [
      { name: "modelConfigId", label: "使用模型", type: "model_selector", default: null },
      { name: "role", label: "节点角色", type: "string", default: "comic_storyboard" },
      { name: "progressStep", label: "进度文案", type: "string", default: "生成分镜表与镜头 Prompt" },
    ],
  },
  {
    type: "character_design",
    category: "视觉资产",
    displayName: "角色定妆",
    description: "为主角/反派/配角生成身份卡与定妆图（正面/侧面/背面锚点，固定面部、发型、服装、否定词）。",
    icon: Image,
    iconName: "image",
    color: "#d946ef",
    defaultWidth: 300,
    defaultHeight: 170,
    defaultData: { kind: "model", iconName: "image" },
    inputSlots: [{ name: "storyboard", type: "json", label: "分镜/角色" }],
    outputSlots: [{ name: "characters", type: "image", label: "角色定妆图" }],
    parameters: [
      { name: "modelConfigId", label: "使用模型", type: "model_selector", default: null },
      { name: "progressStep", label: "进度文案", type: "string", default: "生成角色定妆图" },
    ],
  },
  {
    type: "scene_design",
    category: "视觉资产",
    displayName: "场景设定",
    description: "批量生成场景锚点图，确立画风、光影、空间结构，供关键帧复用。",
    icon: Image,
    iconName: "image",
    color: "#ec4899",
    defaultWidth: 300,
    defaultHeight: 170,
    defaultData: { kind: "model", iconName: "image" },
    inputSlots: [{ name: "storyboard", type: "json", label: "分镜/场景" }],
    outputSlots: [{ name: "scenes", type: "image", label: "场景设定图" }],
    parameters: [
      { name: "modelConfigId", label: "使用模型", type: "model_selector", default: null },
      { name: "progressStep", label: "进度文案", type: "string", default: "生成场景设定图" },
    ],
  },
  {
    type: "keyframe_generator",
    category: "视觉资产",
    displayName: "关键帧生成",
    description: "按分镜逐镜生成首帧/尾帧（风格+场景+角色动作+视角+光影+画幅+否定词）。",
    icon: Image,
    iconName: "image",
    color: "#f472b6",
    defaultWidth: 300,
    defaultHeight: 180,
    defaultData: { kind: "model", iconName: "image" },
    inputSlots: [
      { name: "storyboard", type: "json", label: "分镜表" },
      { name: "characters", type: "image", label: "角色图" },
      { name: "scenes", type: "image", label: "场景图" },
    ],
    outputSlots: [{ name: "keyframe", type: "image", label: "首/尾关键帧" }],
    parameters: [
      { name: "modelConfigId", label: "使用模型", type: "model_selector", default: null },
      { name: "progressStep", label: "进度文案", type: "string", default: "生成每镜首/尾关键帧" },
    ],
  },
  {
    type: "frame_qc",
    category: "视觉资产",
    displayName: "关键帧质检",
    description: "检测角色一致性、画幅、清晰度与违规元素；不合格回退关键帧重生（内联，不计费）。",
    icon: GitBranch,
    iconName: "git-branch",
    color: "#a855f7",
    defaultWidth: 240,
    defaultHeight: 140,
    defaultData: { kind: "condition", iconName: "git-branch" },
    inputSlots: [{ name: "keyframe", type: "image", label: "关键帧" }],
    outputSlots: [{ name: "next", type: "any", label: "通过/重生" }],
    parameters: [{ name: "revisionField", label: "重生字段", type: "string", default: "frameQcFeedback" }],
  },
  {
    type: "image_to_video",
    category: "动态生成",
    displayName: "图生视频",
    description: "用首尾帧控制运动逐镜生成 3-6 秒片段；超长动作片段接力（上段末帧→下段首帧）。",
    icon: Video,
    iconName: "video",
    color: "#f97316",
    defaultWidth: 300,
    defaultHeight: 180,
    defaultData: { kind: "model", iconName: "video" },
    inputSlots: [
      { name: "keyframe", type: "image", label: "首/尾关键帧" },
      { name: "storyboard", type: "json", label: "分镜表" },
    ],
    outputSlots: [{ name: "clip", type: "video", label: "视频片段" }],
    parameters: [
      { name: "modelConfigId", label: "使用模型", type: "model_selector", default: null },
      { name: "progressStep", label: "进度文案", type: "string", default: "逐镜图生视频" },
    ],
  },
  {
    type: "clip_qc",
    category: "动态生成",
    displayName: "片段质检",
    description: "检测脸部崩坏、黑屏、时长、比例与运动稳定性；单镜头失败只重试该镜（内联，不计费）。",
    icon: GitBranch,
    iconName: "git-branch",
    color: "#a855f7",
    defaultWidth: 240,
    defaultHeight: 140,
    defaultData: { kind: "condition", iconName: "git-branch" },
    inputSlots: [{ name: "clip", type: "video", label: "视频片段" }],
    outputSlots: [{ name: "next", type: "any", label: "通过/重试" }],
    parameters: [{ name: "revisionField", label: "重试字段", type: "string", default: "clipQcFeedback" }],
  },
  {
    type: "music_sfx",
    category: "声音剪辑",
    displayName: "配乐/音效",
    description: "按剧情情绪生成或匹配 BGM 与音效（对白最清晰、音效居中、配乐最低）。",
    icon: Mic,
    iconName: "mic",
    color: "#7c3aed",
    defaultWidth: 280,
    defaultHeight: 160,
    defaultData: { kind: "model", iconName: "mic" },
    inputSlots: [{ name: "storyboard", type: "json", label: "分镜/情绪" }],
    outputSlots: [{ name: "audio", type: "audio", label: "BGM/音效" }],
    parameters: [
      { name: "modelConfigId", label: "使用模型", type: "model_selector", default: null },
      { name: "progressStep", label: "进度文案", type: "string", default: "生成 BGM 与音效" },
    ],
  },
  {
    type: "human_review",
    category: "审核交付",
    displayName: "人工审核",
    description: "内容安全/版权/质量/商用合规审核，可配置必审或抽审；通过后进入交付（内联）。",
    icon: CircleDot,
    iconName: "circle-dot",
    color: "#14b8a6",
    defaultWidth: 240,
    defaultHeight: 140,
    defaultData: { kind: "confirm", iconName: "circle-dot" },
    inputSlots: [{ name: "finalVideo", type: "video", label: "成片" }],
    outputSlots: [{ name: "approved", type: "video", label: "审核通过成片" }],
    parameters: [{ name: "reviewMode", label: "审核模式", type: "string", default: "required_before_final" }],
  },
]

export const NODE_CATEGORIES = [...new Set(NODE_TYPES.map((node) => node.category))]
export const WORKFLOW_EXECUTION_NODE_TYPES = [
  "start",
  "field_input",
  "user_input",
  "llm_text",
  "image_model",
  "tts_model",
  "video_model",
  "subtitle",
  "video_output",
  "user_confirm",
  "condition",
  "scene_loop",
  // AI 漫剧 SOP 节点（映射到上述可执行类型，见后端 WorkflowNodeDefType 别名）
  "script_planner",
  "storyboard_generator",
  "character_design",
  "scene_design",
  "keyframe_generator",
  "frame_qc",
  "image_to_video",
  "clip_qc",
  "music_sfx",
  "human_review",
]
export const NODE_TYPE_MAP = new Map(NODE_TYPES.map((node) => [node.type, node]))
