SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS agent_model_configs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  display_name VARCHAR(128) NOT NULL DEFAULT 'Default model',
  config_code VARCHAR(64) NOT NULL DEFAULT 'default',
  provider VARCHAR(64) NOT NULL,
  model_name VARCHAR(128) NOT NULL,
  base_url VARCHAR(512) NULL,
  api_key VARCHAR(512) NULL,
  minimax_group_id VARCHAR(128) NULL,
  console_url VARCHAR(512) NULL,
  balance_url VARCHAR(512) NULL,
  docs_url VARCHAR(512) NULL,
  timeout_seconds INT NOT NULL DEFAULT 60,
  input_token_price_per_1k DECIMAL(18,8) NOT NULL DEFAULT 0,
  output_token_price_per_1k DECIMAL(18,8) NOT NULL DEFAULT 0,
  input_token_price_per_1m DECIMAL(18,8) NOT NULL DEFAULT 0,
  output_token_price_per_1m DECIMAL(18,8) NOT NULL DEFAULT 0,
  billing_unit VARCHAR(32) NOT NULL DEFAULT 'TOKEN_PER_M',
  unit_price DECIMAL(18,8) NOT NULL DEFAULT 0,
  enabled TINYINT NOT NULL DEFAULT 1,
  agent_enabled TINYINT NOT NULL DEFAULT 1,
  is_default TINYINT NOT NULL DEFAULT 0,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_agent_model_configs_code (config_code),
  KEY idx_agent_model_configs_enabled (enabled, is_deleted, id),
  KEY idx_agent_model_configs_agent_enabled (agent_enabled, enabled, is_deleted, is_default, id),
  KEY idx_agent_model_configs_default (is_default, is_deleted, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
