CREATE TABLE IF NOT EXISTS auth_security_events (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  event_type VARCHAR(64) NOT NULL,
  result VARCHAR(16) NOT NULL,
  method VARCHAR(32) NULL,
  user_type VARCHAR(16) NULL,
  user_id BIGINT NULL,
  account_hash VARCHAR(64) NULL,
  account_masked VARCHAR(64) NULL,
  failure_reason VARCHAR(128) NULL,
  ip_address VARCHAR(64) NULL,
  user_agent VARCHAR(512) NULL,
  trace_id VARCHAR(64) NULL,
  country VARCHAR(64) NULL,
  region VARCHAR(64) NULL,
  city VARCHAR(64) NULL,
  latitude DECIMAL(10,6) NULL,
  longitude DECIMAL(10,6) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_auth_security_events_created_at (created_at),
  KEY idx_auth_security_events_type_result (event_type, result, created_at),
  KEY idx_auth_security_events_geo (latitude, longitude, created_at),
  KEY idx_auth_security_events_ip_time (ip_address, created_at)
);
