-- PPT workspace V2: durable asynchronous jobs and platform-controlled exports.

CREATE TABLE IF NOT EXISTS ppt_jobs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  project_id BIGINT NOT NULL,
  root_job_id BIGINT NULL,
  job_type VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'CREATED',
  engine_code VARCHAR(64) NOT NULL,
  external_job_id VARCHAR(128) NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  attempt_no INT NOT NULL DEFAULT 1,
  progress INT NOT NULL DEFAULT 0,
  progress_message VARCHAR(512) NULL,
  request_json JSON NULL,
  result_json JSON NULL,
  error_code VARCHAR(64) NULL,
  error_message VARCHAR(1000) NULL,
  retryable TINYINT NOT NULL DEFAULT 0,
  reserved_credits INT NOT NULL DEFAULT 0,
  actual_credits INT NOT NULL DEFAULT 0,
  credit_state VARCHAR(32) NOT NULL DEFAULT 'NOT_REQUIRED',
  next_poll_at DATETIME NULL,
  lease_owner VARCHAR(128) NULL,
  lease_expires_at DATETIME NULL,
  started_at DATETIME NULL,
  finished_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_ppt_job_user_idempotency (user_id, idempotency_key),
  KEY idx_ppt_job_project_created (project_id, created_at),
  KEY idx_ppt_job_recovery (status, next_poll_at, lease_expires_at),
  KEY idx_ppt_job_external (engine_code, external_job_id),
  KEY idx_ppt_job_root_attempt (root_job_id, attempt_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ppt_exports (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  project_id BIGINT NOT NULL,
  deck_version_id BIGINT NULL,
  job_id BIGINT NOT NULL,
  export_type VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  file_name VARCHAR(255) NULL,
  content_type VARCHAR(128) NULL,
  file_size BIGINT NULL,
  storage_url VARCHAR(1024) NULL,
  checksum_sha256 CHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_ppt_export_job_type (job_id, export_type),
  KEY idx_ppt_export_project_created (project_id, created_at),
  KEY idx_ppt_export_user_project (user_id, project_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
