package com.aiminilab.aitoolmarket.common.enums;

public enum ErrorCode {
    SUCCESS,
    PARAM_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    ADMIN_UNAUTHORIZED,
    ADMIN_FORBIDDEN,
    TOOL_NOT_FOUND,
    TOOL_OFFLINE,
    CREDIT_NOT_ENOUGH,
    TASK_NOT_FOUND,
    TASK_STATUS_INVALID,
    AGENT_SESSION_NOT_FOUND,
    AGENT_RUN_NOT_FOUND,
    AGENT_RUN_NOT_CANCELLABLE,
    AGENT_RATE_LIMITED,
    AGENT_ACTIVE_RUN_LIMIT,
    AGENT_TOOL_NOT_AVAILABLE,
    AGENT_CREDIT_NOT_ENOUGH,
    AGENT_RUN_BUDGET_EXCEEDED,
    AGENT_TOOL_CALL_LIMIT,
    AGENT_MODEL_CALL_LIMIT,
    AGENT_SECURITY_REJECTED,
    MODEL_CALL_FAILED,
    SYSTEM_ERROR
}
